development:
  adapter: mysql2
  encoding: utf8
  username: root
  password: matt22
  socket: /tmp/mysql.sock
  database: see_es_es_development

test:
  adapter: mysql2
  encoding: utf8
  username: root
  password: matt22
  socket: /tmp/mysql.sock
  database: see_es_es_test

production:
  adapter: mysql2
  encoding: utf8
  username: root
  password: matt22
  socket: /tmp/mysql.sock
  database: see_es_es_production
